language: c
 
install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console
  - mozroots --import --sync
 
script:
  - xbuild ./msbuilds/TravisCI.Build.targets
  - nunit-console ./KissSpecifications.UnitTests/bin/Debug/KissSpecifications.UnitTests.dll
